version: '3'

services:
  lawgg-vue:
    image: ${DOCKER_IMAGE_NAME}
    container_name: ${DOCKER_CONTAINER_NAME}
    ports:
      - "${PORT}:80"
    networks:
      - lawgg-network
    volumes:
      - lawgg-nginx:/etc/nginx
    restart: unless-stopped

networks:
  lawgg-network:
    external: true

volumes:
  lawgg-nginx:
    external: true
